name = "Reinos de Aventura"
author = "darknow-web"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "260673c1becfe742efee869bdc0f656b1688e5073286f7377b56944a93f783e1"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
